export const LOAD_GIG_REQUEST = "LOAD_GIG_REQUEST";
export const LOAD_GIG_SUCCESS = "LOAD_GIG_SUCCESS";
export const LOAD_GIG_FAIL = "LOAD_GIG_FAIL";

export const CREATE_GIG_REQUEST = "CREATE_GIG_REQUEST";
export const CREATE_GIG_SUCCESS = "CREATE_GIG_SUCCESS";
export const CREATE_GIG_FAIL = "CREATE_GIG_FAIL";
export const CREATE_GIG_RESET = "CREATE_GIG_RESET";


export const UPDATE_GIG_REQUEST = "UPDATE_GIG_REQUEST";
export const UPDATE_GIG_SUCCESS = "UPDATE_GIG_SUCCESS";
export const UPDATE_GIG_FAIL = "UPDATE_GIG_FAIL";
export const UPDATE_GIG_RESET = "UPDATE_GIG_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
